# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from PyQt6.QtWidgets import QWidget
from framework.plugin_interface import PluginBase
from typing import Any
from typing_extensions import Self
import os
import sys

class DockerPlugin(PluginBase):
    def plugin_name(self: Self) -> str: ...
    def plugin_name_en(self: Self) -> str: ...
    def plugin_version(self: Self) -> str: ...
    def plugin_icon(self: Self) -> str: ...
    def plugin_description(self: Self) -> str: ...
    def plugin_description_en(self: Self) -> str: ...
    def plugin_tags(self: Self) -> list: ...
    def create_widget(self: Self, parent: QWidget) -> QWidget: ...
    def on_activated(self: Self) -> Any: ...
    def on_deactivated(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import os
import logging
import threading
import time
import json
import shlex
import datetime
import PySide6
import PySide6.QtWidgets
import PySide6.QtCore
import PySide6.QtGui
import paramiko
import ntpath
import re
import PyQt6
import PyQt6.QtWidgets
import framework
import framework.plugin_interface